//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adi_ad_informacao
    {
        public int adi_id_adi { get; set; }
        public int adi_id_usu { get; set; }
        public string adi_nom_script_path { get; set; }
        public string adi_nom_email { get; set; }
        public string adi_nom_description { get; set; }
    }
}
