//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbContextAdUsuarios : DbContext
    {
        public DbContextAdUsuarios()
            : base("name=DbContextAdUsuarios")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adi_ad_informacao> adi_ad_informacao { get; set; }
        public virtual DbSet<gru_grupo> gru_grupo { get; set; }
        public virtual DbSet<ild_informacoes_ldap> ild_informacoes_ldap { get; set; }
        public virtual DbSet<pus_perfil_usuario> pus_perfil_usuario { get; set; }
        public virtual DbSet<set_setor> set_setor { get; set; }
        public virtual DbSet<use_usuario_setor> use_usuario_setor { get; set; }
        public virtual DbSet<usu_usuario> usu_usuario { get; set; }
    }
}
