//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ase_aprovacao_setor
    {
        public int ase_id_ase { get; set; }
        public int ase_id_set { get; set; }
        public System.DateTime ase_dti_aprovacao { get; set; }
        public Nullable<System.DateTime> ase_dtf_aprovacao { get; set; }
        public System.DateTime ase_dat_cadastro { get; set; }
        public int ase_id_use_cadastro { get; set; }
    }
}
