//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_assinatura
    {
        public int ass_id_ass { get; set; }
        public string ass_des_assinatura { get; set; }
        public int ass_id_use { get; set; }
        public bool ass_flg_atualizado { get; set; }
    }
}
