//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cas_controle_acesso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cas_controle_acesso()
        {
            this.com_controle_menu = new HashSet<com_controle_menu>();
        }
    
        public int cas_id_cas { get; set; }
        public string cas_id_ip { get; set; }
        public string cas_nom_maquina { get; set; }
        public int cas_id_use { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<com_controle_menu> com_controle_menu { get; set; }
    }
}
