//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_controle_menu
    {
        public int com_id_com { get; set; }
        public int com_id_cas { get; set; }
        public int com_id_men { get; set; }
        public System.DateTime com_dat_acesso { get; set; }
    
        public virtual cas_controle_acesso cas_controle_acesso { get; set; }
        public virtual men_menu men_menu { get; set; }
    }
}
