//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dme_destinatario_mensagem
    {
        public int dme_id_dme { get; set; }
        public int dme_id_tde { get; set; }
        public int dme_id_men { get; set; }
        public int dme_id_use { get; set; }
        public Nullable<System.DateTime> dme_dat_leitura { get; set; }
        public bool dme_flg_leitura { get; set; }
        public bool dme_flg_msg_automatica { get; set; }
        public System.DateTime dme_dat_cadastro { get; set; }
    
        public virtual men_mensagem men_mensagem { get; set; }
        public virtual tde_tipo_destinatario tde_tipo_destinatario { get; set; }
    }
}
