//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ild_informacoes_ldap
    {
        public int ild_id_ild { get; set; }
        public int ild_id_usu { get; set; }
        public string ild_cod_guid { get; set; }
        public string ild_nom_usuario { get; set; }
        public string ild_nom_usuario_completo { get; set; }
        public string ild_nom_usuario_primeiro { get; set; }
        public string ild_nom_usuario_ultimo { get; set; }
        public string ild_nom_iniciais { get; set; }
        public string ild_nom_login { get; set; }
        public string ild_nom_titulo { get; set; }
        public string ild_des_descricao { get; set; }
        public string ild_des_informacao { get; set; }
        public string ild_num_telefone { get; set; }
        public string ild_nom_grupos { get; set; }
        public string ild_nom_email { get; set; }
        public string ild_nom_escritorio { get; set; }
        public string ild_nom_companhia { get; set; }
        public string ild_nom_departamento { get; set; }
        public string ild_nom_local { get; set; }
        public string ild_nom_script_path { get; set; }
        public Nullable<System.DateTime> ild_dat_criacao { get; set; }
        public Nullable<System.DateTime> ild_dat_atualizacao { get; set; }
        public string ild_dat_fim_bloqueio { get; set; }
        public string ild_dat_ultimo_logon { get; set; }
        public string ild_dat_ultimo_logon_stamp { get; set; }
    
        public virtual usu_usuario usu_usuario { get; set; }
    }
}
