//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class los_log_sistema
    {
        public long los_id_los { get; set; }
        public int los_num_nivel { get; set; }
        public string los_nom_categoria { get; set; }
        public double los_log_time { get; set; }
        public string los_des_mensagem { get; set; }
        public int los_id_usu { get; set; }
        public System.DateTime los_data_hora { get; set; }
    }
}
