//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class max_mensagem_anexo
    {
        public int max_id_max { get; set; }
        public string max_nom_arquivo { get; set; }
        public Nullable<int> max_num_tamanho { get; set; }
        public byte[] max_bin_arquivo { get; set; }
        public string max_nom_tipo { get; set; }
        public string max_url_caminho { get; set; }
        public System.DateTime max_dat_cadastro { get; set; }
        public int max_id_men { get; set; }
    
        public virtual men_mensagem men_mensagem { get; set; }
    }
}
