//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mde_mensagem_detalhes
    {
        public int mde_id_mde { get; set; }
        public bool mde_flg_importante { get; set; }
        public int mde_id_men { get; set; }
        public int mde_id_use { get; set; }
    
        public virtual men_mensagem men_mensagem { get; set; }
    }
}
