//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mea_mensagem_aprovada
    {
        public int mea_id_mea { get; set; }
        public int mea_id_men { get; set; }
        public bool mea_flg_mensagem_aprovada { get; set; }
        public bool mea_flg_reavaliacao { get; set; }
        public string mea_des_motivo { get; set; }
        public System.DateTime mea_dat_registro { get; set; }
        public int mea_id_use { get; set; }
        public Nullable<int> mea_id_use_secretaria { get; set; }
    
        public virtual men_mensagem men_mensagem { get; set; }
    }
}
