//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class men_mensagem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public men_mensagem()
        {
            this.cnu_controle_numeros = new HashSet<cnu_controle_numeros>();
            this.dme_destinatario_mensagem = new HashSet<dme_destinatario_mensagem>();
            this.max_mensagem_anexo = new HashSet<max_mensagem_anexo>();
            this.mde_mensagem_detalhes = new HashSet<mde_mensagem_detalhes>();
            this.mea_mensagem_aprovada = new HashSet<mea_mensagem_aprovada>();
            this.men_mensagem1 = new HashSet<men_mensagem>();
            this.men_mensagem11 = new HashSet<men_mensagem>();
            this.meq_mensagem_arquivada = new HashSet<meq_mensagem_arquivada>();
            this.rem_remetente = new HashSet<rem_remetente>();
            this.mra_mensagem_rascunho = new HashSet<mra_mensagem_rascunho>();
        }


        public int men_id_men { get; set; }
        public string men_num_autenticacao { get; set; }
        public string men_nom_titulo { get; set; }
        public string men_des_mensagem { get; set; }
        public int men_id_tme { get; set; }
        public System.DateTime men_dat_cadastro { get; set; }
        public Nullable<int> men_id_men_referencia { get; set; }
        public Nullable<int> men_id_men_pai { get; set; }
        public bool men_flg_aprovacao { get; set; }
        public int men_id_sme { get; set; }


        public const string CAIXA_ENTRADA = "caixa_entrada"; 
        public const string ENVIADAS = "enviadas"; 
        public const string MODELO = "modelo";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cnu_controle_numeros> cnu_controle_numeros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dme_destinatario_mensagem> dme_destinatario_mensagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<max_mensagem_anexo> max_mensagem_anexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mde_mensagem_detalhes> mde_mensagem_detalhes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mea_mensagem_aprovada> mea_mensagem_aprovada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<men_mensagem> men_mensagem1 { get; set; }
        public virtual men_mensagem men_mensagem2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<men_mensagem> men_mensagem11 { get; set; }
        public virtual men_mensagem men_mensagem3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meq_mensagem_arquivada> meq_mensagem_arquivada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rem_remetente> rem_remetente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mra_mensagem_rascunho> mra_mensagem_rascunho { get; set; }
        public virtual sme_status_mensagem sme_status_mensagem { get; set; }
        public virtual tme_tipo_mensagem tme_tipo_mensagem { get; set; }
    }
}
