//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class men_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public men_menu()
        {
            this.com_controle_menu = new HashSet<com_controle_menu>();
            this.pem_perfil_menu = new HashSet<pem_perfil_menu>();
            this.ume_usuario_menu = new HashSet<ume_usuario_menu>();
        }
    
        public int men_id_men { get; set; }
        public string men_nom_menu { get; set; }
        public string men_htm_icon { get; set; }
        public string men_nom_action { get; set; }
        public string men_nom_controller { get; set; }
        public bool men_flg_menu_guest { get; set; }
        public bool men_flg_menu_admin { get; set; }
        public bool men_flg_modulo { get; set; }
        public bool men_flg_ativo { get; set; }
        public Nullable<int> men_id_men_pai { get; set; }
        public int men_num_posicao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<com_controle_menu> com_controle_menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pem_perfil_menu> pem_perfil_menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ume_usuario_menu> ume_usuario_menu { get; set; }
    }
}
