//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mra_mensagem_rascunho
    {
        public int mra_id_mra { get; set; }
        public int mra_id_men { get; set; }
        public string mra_ids_use_dest { get; set; }
        public string mra_ids_use_dest_copia { get; set; }
        public string mra_ids_apensamentos { get; set; }
        public System.DateTime mra_dat_rascunho { get; set; }
    
        public virtual men_mensagem men_mensagem { get; set; }
    }
}
