//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pse_permissoes_secretaria
    {
        public int pse_id_pse { get; set; }
        public int pse_id_uau { get; set; }
        public bool pse_flg_visualizar { get; set; }
        public bool pse_flg_responder_encaminhar { get; set; }
        public bool pse_flg_aprovar_reprovar { get; set; }
        public bool pse_flg_criar_circular { get; set; }
    
        public virtual uau_usuario_autorizado uau_usuario_autorizado { get; set; }
    }
}
