//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class set_setor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public set_setor()
        {
            this.set_setor1 = new HashSet<set_setor>();
            this.set_setor11 = new HashSet<set_setor>();
            this.use_usuario_setor = new HashSet<use_usuario_setor>();
            this.usu_usuario = new HashSet<usu_usuario>();
        }
    
        public int set_id_set { get; set; }
        public string set_nom_sigla { get; set; }
        [DisplayAttribute(Name = "Nome Setor")]
        public string set_nom_setor { get; set; }
        public int set_id_set_pai { get; set; }
        public int set_id_set_gerenciador { get; set; }
        public bool set_flg_ativo { get; set; }
        public Nullable<System.DateTime> set_dat_desativacao { get; set; }
        public bool set_flg_setor_oficial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<set_setor> set_setor1 { get; set; }
        public virtual set_setor set_setor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<set_setor> set_setor11 { get; set; }
        public virtual set_setor set_setor3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<use_usuario_setor> use_usuario_setor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usu_usuario> usu_usuario { get; set; }
    }
}
