//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tnu_tipo_numeracao
    {
        public int tnu_id_tnu { get; set; }
        public string tnu_nom_tipo { get; set; }
        public bool tnu_flg_ci { get; set; }
    }
}
