//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ume_usuario_menu
    {
        public int ume_id_ume { get; set; }
        public int ume_id_usu { get; set; }
        public int ume_id_men { get; set; }
    
        public virtual men_menu men_menu { get; set; }
    }
}
