//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class use_usuario_setor
    {
        public int use_id_use { get; set; }
        public int use_id_pus { get; set; }
        public int use_id_usu { get; set; }
        public int use_id_set { get; set; }
        public bool use_flg_ativo { get; set; }
        public bool use_flg_padrao { get; set; }
    
        public virtual pus_perfil_usuario pus_perfil_usuario { get; set; }
        public virtual set_setor set_setor { get; set; }
        public virtual usu_usuario usu_usuario { get; set; }
    }
}
