//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ard_arvore_destinatario_
    {
        public int id { get; set; }
        public int root { get; set; }
        public int id_setor { get; set; }
        public int id_sub_setor { get; set; }
        public int id_sub_sub_setor { get; set; }
        public Nullable<decimal> perfil_order { get; set; }
        public string setor_order { get; set; }
        public Nullable<long> lft { get; set; }
        public Nullable<long> rgt { get; set; }
        public int lvl { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public int icon_type { get; set; }
        public int active { get; set; }
        public int selected { get; set; }
        public int disabled { get; set; }
        public int @readonly { get; set; }
        public int visible { get; set; }
        public int collapsed { get; set; }
        public int movable_u { get; set; }
        public int movable_d { get; set; }
        public int movable_l { get; set; }
        public int movable_r { get; set; }
        public int removable { get; set; }
        public int removable_all { get; set; }
    }
}
