//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_mau_mensagem_arquivamento_usuario
    {
        public int qef_id_use { get; set; }
        public Nullable<int> qef_id_men_pai { get; set; }
        public Nullable<int> qef_id_men { get; set; }
    }
}
