//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_mfv_mensagem_pai_filha_valida
    {
        public int mfv_id_use { get; set; }
        public Nullable<int> mfv_id_men_pai { get; set; }
        public int mfv_id_men { get; set; }
    }
}
