//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_mfa_mensagem_pai_filha_arquivada
    {
        public int mfa_id_use { get; set; }
        public int mfa_id_set_gerenciador { get; set; }
        public Nullable<int> mfa_id_men_pai { get; set; }
        public int mfa_id_men { get; set; }
        public int mfa_flg_pendente_aprovacao { get; set; }
    }
}
