//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_nlp_notificacao_nao_lida_pendente
    {
        public int nlp_id_use { get; set; }
        public Nullable<int> nlp_qtd_nao_lida_pendente { get; set; }
        public int nlp_flg_nao_lida_pendente { get; set; }
    }
}
