//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_nnl_notificacao_nao_lida
    {
        public int nnl_id_use { get; set; }
        public Nullable<int> nnl_qtd_nao_lida { get; set; }
        public int nnl_flg_nao_lida { get; set; }
    }
}
