//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_npa_notificacao_pendente_aprovacao
    {
        public int npa_id_use { get; set; }
        public int npa_id_set_gerenciador { get; set; }
        public Nullable<int> npa_qtd_pendente { get; set; }
        public int npa_flg_pendente { get; set; }
    }
}
