//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_qfv_quantitativo_mensagem_filha_valida
    {
        public int qfv_id_use { get; set; }
        public Nullable<int> qfv_id_men_pai { get; set; }
        public Nullable<int> qfv_qtd_filha { get; set; }
        public Nullable<int> qfv_qtd_filha_externa { get; set; }
    }
}
