//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_qmd_quantitativo_mensagem_destinatario
    {
        public Nullable<int> qmd_id_men { get; set; }
        public int qmd_id_use { get; set; }
        public Nullable<int> qmd_num_quantitativo { get; set; }
    }
}
