//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_qmp_quantitativo_mensagem_nao_lida_pai
    {
        public int qmp_id_use { get; set; }
        public int qmp_id_set_gerenciador { get; set; }
        public Nullable<int> qmp_id_men_pai { get; set; }
        public Nullable<int> qmp_qtd_mensagem { get; set; }
    }
}
