//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_qpa_quantitativo_pendente_aprovacao_pai
    {
        public int qpa_id_set_gerenciador { get; set; }
        public Nullable<int> qpa_id_men_pai { get; set; }
        public Nullable<int> qpa_qtd_pendente { get; set; }
    }
}
