//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ush_usuario_autorizado_historico
    {
        public Nullable<int> ush_id_uau { get; set; }
        public int ush_id_pus { get; set; }
        public int ush_id_use { get; set; }
        public int ush_id_set { get; set; }
    }
}
